"""add postmark settings

Revision ID: 0fa88a7bfb09
Revises: 41c29c12c54b
Create Date: 2026-04-13 01:59:22.898882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa88a7bfb09'
down_revision = '41c29c12c54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postmark_api_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('postmark_sender_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('postmark_sender_email')
        batch_op.drop_column('postmark_api_token')

    # ### end Alembic commands ###
