"""add seo and analytics fields

Revision ID: 153fbdc5bdd7
Revises: 8d74056b256a
Create Date: 2026-04-13 02:11:55.255130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153fbdc5bdd7'
down_revision = '8d74056b256a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('google_analytics_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('google_analytics_id')
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')

    # ### end Alembic commands ###
