"""Add layout and module style fields

Revision ID: 208b1b6538a8
Revises: 5b1967e2d863
Create Date: 2026-04-09 14:31:19.961830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208b1b6538a8'
down_revision = '5b1967e2d863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('site_settings', ... ) # Already exists from previous attempt
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('css_class', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('show_title', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.String(length=50), nullable=False, server_default='default'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('layout')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('show_title')
        batch_op.drop_column('css_class')

    op.drop_table('site_settings')
    # ### end Alembic commands ###
