"""add shop discounts and order fields

Revision ID: 255155e149b8
Revises: ddabe2935101
Create Date: 2026-04-13 12:44:16.511314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255155e149b8'
down_revision = 'ddabe2935101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('min_purchase', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_code')

    op.drop_table('shop_discounts')
    # ### end Alembic commands ###
