"""Add posts_per_page to SiteSettings

Revision ID: 41c29c12c54b
Revises: 888e3ebb79da
Create Date: 2026-04-12 19:49:05.147592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c29c12c54b'
down_revision = '888e3ebb79da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posts_per_page', sa.Integer(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('posts_per_page')

    # ### end Alembic commands ###
