"""Expand shop models for types and options v2

Revision ID: 48d67fb12d9a
Revises: 2def2bc106e6
Create Date: 2026-04-12 18:24:48.098279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d67fb12d9a'
down_revision = '2def2bc106e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_shop_orders')
    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_json', sa.Text(), nullable=True))
        batch_op.alter_column('payment_gateway',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('gateway_order_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('options_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.drop_column('options_json')
        batch_op.drop_column('product_type')

    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.alter_column('gateway_order_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('payment_gateway',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('items_json')

    op.create_table('_alembic_tmp_shop_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payment_gateway', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gateway_order_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('items_json', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
