"""add customer_name to order

Revision ID: 4daaeb3c5f4d
Revises: 48d67fb12d9a
Create Date: 2026-04-12 18:35:32.485076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4daaeb3c5f4d'
down_revision = '48d67fb12d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
