"""add media folders

Revision ID: 5b2b373d5b0d
Revises: 255155e149b8
Create Date: 2026-04-13 12:46:39.218980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2b373d5b0d'
down_revision = '255155e149b8'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'media_folders' not in tables:
        op.create_table('media_folders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['media_folders.id'], name='fk_media_folders_parent'),
        sa.PrimaryKeyConstraint('id')
        )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_media_files_folder', 'media_folders', ['folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_media_files_folder', type_='foreignkey')
        batch_op.drop_column('folder_id')

    op.drop_table('media_folders')
    # ### end Alembic commands ###
