"""add form and submission models

Revision ID: 8d74056b256a
Revises: 0fa88a7bfb09
Create Date: 2026-04-13 02:01:57.760258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d74056b256a'
down_revision = '0fa88a7bfb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('email_recipient', sa.String(length=255), nullable=True),
    sa.Column('success_message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_submissions_form_id'), ['form_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_submissions_form_id'))

    op.drop_table('form_submissions')
    op.drop_table('forms')
    # ### end Alembic commands ###
