"""Add menu_id to Page

Revision ID: 8f6bc3046788
Revises: f47245936f7b
Create Date: 2026-04-09 15:54:05.549285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6bc3046788'
down_revision = 'f47245936f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_page_menu', 'menus', ['menu_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_page_menu', type_='foreignkey')
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###
