"""add gemini api key

Revision ID: 91dc670a28c6
Revises: e4a75d87cd3f
Create Date: 2026-04-13 13:07:16.276762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dc670a28c6'
down_revision = 'e4a75d87cd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemini_api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('gemini_api_key')

    # ### end Alembic commands ###
