"""add shipping address to order

Revision ID: 96baf3396640
Revises: 4daaeb3c5f4d
Create Date: 2026-04-12 18:41:26.499432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96baf3396640'
down_revision = '4daaeb3c5f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_zip', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_zip')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###
