"""add seo fields to pages posts products

Revision ID: 99af56df18a2
Revises: 153fbdc5bdd7
Create Date: 2026-04-13 02:23:45.633168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99af56df18a2'
down_revision = '153fbdc5bdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=500), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=500), nullable=True))

    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_products', schema=None) as batch_op:
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_description')

    # ### end Alembic commands ###
