"""Add module assignments

Revision ID: cc6cc8a04b9e
Revises: 8f6bc3046788
Create Date: 2026-04-10 10:01:46.201728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6cc8a04b9e'
down_revision = '8f6bc3046788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('module_assignments',
    # sa.Column('module_id', sa.Integer(), nullable=False),
    # sa.Column('menu_item_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    # sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    # sa.PrimaryKeyConstraint('module_id', 'menu_item_id')
    # )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_type', sa.String(length=20), server_default='all', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('assignment_type')

    op.drop_table('module_assignments')
    # ### end Alembic commands ###
