"""add webhook_url to forms

Revision ID: ddabe2935101
Revises: 99af56df18a2
Create Date: 2026-04-13 12:42:30.700332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddabe2935101'
down_revision = '99af56df18a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###
