"""add_advanced_media_fields

Revision ID: e120c86f6658
Revises: 91dc670a28c6
Create Date: 2026-04-14 11:08:06.685703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e120c86f6658'
down_revision = '91dc670a28c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focal_point_x', sa.Integer(), nullable=False, server_default='50'))
        batch_op.add_column(sa.Column('focal_point_y', sa.Integer(), nullable=False, server_default='50'))
        batch_op.add_column(sa.Column('webp_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('responsive_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_column('responsive_data')
        batch_op.drop_column('webp_path')
        batch_op.drop_column('focal_point_y')
        batch_op.drop_column('focal_point_x')
        batch_op.drop_column('caption')
        batch_op.drop_column('alt_text')

    # ### end Alembic commands ###
