"""add views tracking

Revision ID: e4a75d87cd3f
Revises: 5b2b373d5b0d
Create Date: 2026-04-13 12:53:56.890638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a75d87cd3f'
down_revision = '5b2b373d5b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('views')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
