"""Add config_json to site settings

Revision ID: f47245936f7b
Revises: 208b1b6538a8
Create Date: 2026-04-09 14:42:25.799735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47245936f7b'
down_revision = '208b1b6538a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_json', sa.Text(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('config_json')

    # ### end Alembic commands ###
